# Generated by Django 2.0.7 on 2018-07-27 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Queja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('imagen', models.ImageField(upload_to='imgs/')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appQuejas.Categoria')),
                ('comentarios', models.ManyToManyField(to='appQuejas.Comentario')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=80, unique=True)),
                ('contrasena', models.CharField(max_length=50)),
                ('nombrePersona', models.CharField(max_length=255)),
                ('apellidoPersona', models.CharField(max_length=255)),
                ('correo', models.CharField(max_length=255, unique=True)),
                ('numeroContacto', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='queja',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appQuejas.Usuario'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appQuejas.Usuario'),
        ),
    ]
