# Generated by Django 2.1 on 2018-08-14 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.CharField(max_length=500)),
                ('fechaCreacion', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Queja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('fechaCreacion', models.DateField(auto_now=True)),
                ('imagen', models.ImageField(upload_to='imgs/')),
                ('descripcion', models.CharField(max_length=1000)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appQuejas.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Usertype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoUsuario', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreDeUsuario', models.CharField(max_length=80, unique=True)),
                ('contrasena', models.CharField(max_length=50)),
                ('nombrePersona', models.CharField(max_length=255)),
                ('apellidoPersona', models.CharField(max_length=255)),
                ('correo', models.CharField(max_length=255, unique=True)),
                ('numeroContacto', models.CharField(max_length=50)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appQuejas.Usertype')),
            ],
        ),
        migrations.AddField(
            model_name='queja',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appQuejas.Usuario'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='queja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appQuejas.Queja'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appQuejas.Usuario'),
        ),
    ]
