# Generated by Django 2.0.7 on 2018-07-27 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appQuejas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='fechaCreacion',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='queja',
            name='fechaCreacion',
            field=models.DateField(auto_now=True),
        ),
    ]
